
name: "Duino Coin PC Miner"
description: "Mine Duino coins in Home Assistant"
version: "1.0.0"
slug: "ruiner"
init: false
arch:
  - armv7

apparmor: true
backup: hot
tmpfs: true
stage: deprecated

options:
  username: ""
  minig_key: ""
  rig_name: ""
  start_diff: "LOW"
  threads: "2"
schema:
  username: str
  minig_key: str
  rig_name: str
  start_diff: str
  threads: int
